// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRZuq2hiC5Z6JvWvzuo-OyC5E4nMs2i-s',
    appId: '1:998185916009:web:5c9b196cbfc3917a32f4f8',
    messagingSenderId: '998185916009',
    projectId: 'financialfirebase-7d826',
    authDomain: 'financialfirebase-7d826.firebaseapp.com',
    databaseURL: 'https://financialfirebase-7d826-default-rtdb.firebaseio.com',
    storageBucket: 'financialfirebase-7d826.appspot.com',
    measurementId: 'G-K8ZGVJW8R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfnjMxJ90D2PDTBuJ0VkhvU3SC7Zn2aFI',
    appId: '1:998185916009:android:31f02fe6baa6df1d32f4f8',
    messagingSenderId: '998185916009',
    projectId: 'financialfirebase-7d826',
    databaseURL: 'https://financialfirebase-7d826-default-rtdb.firebaseio.com',
    storageBucket: 'financialfirebase-7d826.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfT8XBjmOCsSG-aHyEzI01nNGjqpRFMyQ',
    appId: '1:998185916009:ios:ddafeb32c2e96ed032f4f8',
    messagingSenderId: '998185916009',
    projectId: 'financialfirebase-7d826',
    databaseURL: 'https://financialfirebase-7d826-default-rtdb.firebaseio.com',
    storageBucket: 'financialfirebase-7d826.appspot.com',
    iosBundleId: 'com.example.financialGoalsTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfT8XBjmOCsSG-aHyEzI01nNGjqpRFMyQ',
    appId: '1:998185916009:ios:eaee5babb7cf370532f4f8',
    messagingSenderId: '998185916009',
    projectId: 'financialfirebase-7d826',
    databaseURL: 'https://financialfirebase-7d826-default-rtdb.firebaseio.com',
    storageBucket: 'financialfirebase-7d826.appspot.com',
    iosBundleId: 'com.example.financialGoalsTracker.RunnerTests',
  );
}
